# Generated by Django 2.2.2 on 2019-06-16 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('estado', models.CharField(default='Afazer', max_length=10)),
                ('dtstatus', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
