# Generated by Django 2.2.2 on 2019-06-18 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KanBan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='dtprazo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
